---
abstract: 'collaborative IRC helper'
author:
  - 'Martín Ferrari'
  - 'Damyan Ivanov'
  - 'gregor herrmann'
build_requires: {}
configure_requires:
  Module::Build: 0.40
  perl: 5.010
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-KGB
no_index:
  directory:
    - privinc
provides:
  App::KGB:
    file: lib/App/KGB.pm
    version: 1.30
  App::KGB::API:
    file: lib/App/KGB/API.pm
    version: 4
  App::KGB::Change:
    file: lib/App/KGB/Change.pm
    version: 1.22
  App::KGB::Client:
    file: lib/App/KGB/Client.pm
    version: 1.28
  App::KGB::Client::CVS:
    file: lib/App/KGB/Client/CVS.pm
    version: 1.23
  App::KGB::Client::Fake:
    file: lib/App/KGB/Client/Fake.pm
    version: 1.17
  App::KGB::Client::Git:
    file: lib/App/KGB/Client/Git.pm
    version: 1.28
  App::KGB::Client::RelayMsg:
    file: lib/App/KGB/Client/RelayMsg.pm
    version: 1.27
  App::KGB::Client::ServerRef:
    file: lib/App/KGB/Client/ServerRef.pm
    version: 1.28
  App::KGB::Client::Subversion:
    file: lib/App/KGB/Client/Subversion.pm
    version: 1.27
  App::KGB::Commit:
    file: lib/App/KGB/Commit.pm
    version: 1.27
  App::KGB::Commit::Tag:
    file: lib/App/KGB/Commit/Tag.pm
    version: 1.28
  App::KGB::Painter:
    file: lib/App/KGB/Painter.pm
    version: 1.27
  JSON::RPC::Client::Any:
    file: lib/JSON/RPC/Client/Any.pm
    version: 1.28
  WWW::Shorten::Debli:
    file: lib/WWW/Shorten/Debli.pm
    version: 0.1
requires:
  Class::Accessor: 0
  Digest::SHA: 0
  DirHandle: 0
  File::Touch: 0
  Git: 0
  IPC::Run: 0
  IPC::System::Simple: 0
  JSON: 0
  JSON::RPC::Client: 0
  POE: 0
  POE::Component::IRC: 5.56
  POE::Component::Server::SOAP: 0
  Proc::PID::File: 0
  SOAP::Lite: 0
  SVN::Core: 0
  SVN::Fs: 0
  SVN::Repos: 0
  Schedule::RateLimiter: 0
  Time::Piece: 0
  WWW::Shorten: 0
  YAML: 0
  perl: 5.010
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
version: 1.30
x_test_requires:
  Git: 0
  SVN::Core: 0
  SVN::Fs: 0
  SVN::Repos: 0
  Test::Compile: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0.92
  YAML: 0
  autodie: 0
  perl: 5.010
