---
abstract: 'collaborative IRC helper'
author:
  - unknown
build_requires:
  Test::Compile: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0.92
  autodie: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-KGB
no_index:
  directory:
    - privinc
provides:
  App::KGB:
    file: lib/App/KGB.pm
    version: 1.16
  App::KGB::Change:
    file: lib/App/KGB/Change.pm
    version: 0
  App::KGB::Client:
    file: lib/App/KGB/Client.pm
    version: 0
  App::KGB::Client::CVS:
    file: lib/App/KGB/Client/CVS.pm
    version: 0
  App::KGB::Client::Git:
    file: lib/App/KGB/Client/Git.pm
    version: 0
  App::KGB::Client::ServerRef:
    file: lib/App/KGB/Client/ServerRef.pm
    version: 0
  App::KGB::Client::Subversion:
    file: lib/App/KGB/Client/Subversion.pm
    version: 0
  App::KGB::Commit:
    file: lib/App/KGB/Commit.pm
    version: 0
requires:
  Class::Accessor: 0
  Digest::SHA: 0
  DirHandle: 0
  File::Touch: 0
  Git: 0
  IPC::System::Simple: 0
  POE: 0
  POE::Component::IRC: 5.56
  POE::Component::Server::SOAP: 0
  Proc::PID::File: 0
  SOAP::Lite: 0
  Schedule::RateLimiter: 0
  YAML: 0
  perl: 5.010
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
version: 1.16
